socket = "server.sock"

[logger]
type = "Trell.ConsoleLogger"

[storage]
path = "C:/Temp/TrellUserData"

[worker.pool]
size = 10

[worker.limits]
max_startup_duration = "1s"
max_execution_duration = "15m"
grace_period = "10s"

[[Serilog.WriteTo]]
Name = "Console"
Args = { "OutputTemplate" = "[{Timestamp:HH:mm:ss} {ProcessId} {Level:u3}] {Message:lj}{NewLine}{Exception}" }

[Serilog.MinimumLevel]
Default = "Debug"
Override = { "Microsoft" = "Warning" }
